# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='connection.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63onnection.proto\"5\n\x11\x43onnectionMessage\x12\x10\n\x08location\x18\x01 \x01(\t\x12\x0e\n\x06person\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"@\n\x15\x43onnectionMessageList\x12\'\n\x0b\x63onnections\x18\x01 \x03(\x0b\x32\x12.ConnectionMessage2l\n\x11\x43onnectionService\x12\x30\n\x06\x43reate\x12\x12.ConnectionMessage\x1a\x12.ConnectionMessage\x12%\n\x03Get\x12\x06.Empty\x1a\x16.ConnectionMessageListb\x06proto3'
)




_CONNECTIONMESSAGE = _descriptor.Descriptor(
  name='ConnectionMessage',
  full_name='ConnectionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='ConnectionMessage.location', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='person', full_name='ConnectionMessage.person', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=73,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=82,
)


_CONNECTIONMESSAGELIST = _descriptor.Descriptor(
  name='ConnectionMessageList',
  full_name='ConnectionMessageList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='connections', full_name='ConnectionMessageList.connections', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=148,
)

_CONNECTIONMESSAGELIST.fields_by_name['connections'].message_type = _CONNECTIONMESSAGE
DESCRIPTOR.message_types_by_name['ConnectionMessage'] = _CONNECTIONMESSAGE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['ConnectionMessageList'] = _CONNECTIONMESSAGELIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectionMessage = _reflection.GeneratedProtocolMessageType('ConnectionMessage', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONMESSAGE,
  '__module__' : 'connection_pb2'
  # @@protoc_insertion_point(class_scope:ConnectionMessage)
  })
_sym_db.RegisterMessage(ConnectionMessage)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'connection_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

ConnectionMessageList = _reflection.GeneratedProtocolMessageType('ConnectionMessageList', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONMESSAGELIST,
  '__module__' : 'connection_pb2'
  # @@protoc_insertion_point(class_scope:ConnectionMessageList)
  })
_sym_db.RegisterMessage(ConnectionMessageList)



_CONNECTIONSERVICE = _descriptor.ServiceDescriptor(
  name='ConnectionService',
  full_name='ConnectionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=150,
  serialized_end=258,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='ConnectionService.Create',
    index=0,
    containing_service=None,
    input_type=_CONNECTIONMESSAGE,
    output_type=_CONNECTIONMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='ConnectionService.Get',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CONNECTIONMESSAGELIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONNECTIONSERVICE)

DESCRIPTOR.services_by_name['ConnectionService'] = _CONNECTIONSERVICE

# @@protoc_insertion_point(module_scope)
